### PR TITLE
Bump Backport.System.Threading.Lock to 1.1.1

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**
Made SecurityTransparent.

### CODE REVIEW

**Comment by WeihanLi** [comment]
Looked into the source code and did some benchmarking, the implementation is not different from the source in
 https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Threading/Lock.cs 

do not think it will bring benefits as expected, closing now

lock-object

lock-Lock

**Comment by MarkCiliaVincenti** [comment]
I'm not sure what you mean. Neither code in your screenshots seem to be using System.Threading.Lock, which on top is only available from .NET 9.0 onwards.

Please take a look at https://github.com/MarkCiliaVincenti/Backport.System.Threading.Lock/tree/master/Backport.System.Threading.Lock.Benchmarks for benchmarks.

What the backport dependency does is allow you to use the more performant locking code in System.Threading.Lock on .NET 9.0, 
 on code that also compiles on .NET 8.0 and earlier.

You simply cannot do this on .NET 8.0 for example:

```
var myLock = new System.Threading.Lock();
using (myLock.EnterScope())
{
    // do this and that
}
```

But if you add the Backport.System.Threading.Lock dependency, it does. It won't run faster than a lock on an object in .NET 8.0 but it will run faster than a lock on an object in .NET 9.0.

**Comment by WeihanLi** [comment]
>  It won't run faster than a lock on an object in .NET 8.0

That's exactly what I want to express, not faster but slower for the frameworks prior to `net9.0`, the implementation is via `Monitor` which is exactly how the `lock` keyword works.

> What the backport dependency does is allow you to use the more performant locking code in `System.Threading.Lock` on .NET 9.0, on code that also compiles on .NET 8.0 and earlier.

we could use the implicit using to unify the `Lock` usage without introducing new types for `net8.0` etc...

```xml
<Using Include="System.Object" Alias="Lock" Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net9.0'))" />
```

It seems too heavy and has no performance benefits for me to add a reference for `Backport.System.Threading.Lock`

**Comment by MarkCiliaVincenti** [comment]
I have added a benchmark project. The use of `Backport.System.Threading.Lock` on .NET 8.0 or earlier does NOT increase memory allocations nor does it reduce performance at all.

But if you do the tests on .NET 9.0, even with the use of `Backport.System.Threading.Lock`, you will see it is faster to lock using the Lock class than if you use object for locking.

In short:
.NET 8.0 or ealier: no difference
.NET 9.0 and future releases: performance benefit.

**Comment by MarkCiliaVincenti** [comment]
> ```
> <Using Include="System.Object" Alias="Lock" Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net9.0'))" />
> ```

Also about this part, yes it works but then you cannot use any of the methods and properties found in `System.Threading.Lock` but the only thing you can do is a `lock (variable)`.

**Comment by WeihanLi** [comment]
> .NET 8.0 or ealier: no difference

Since the implementation is based on `Monitor` https://github.com/MarkCiliaVincenti/Backport.System.Threading.Lock/blob/12fa70bf065a2027fedaebb258a7e2d4d85a1e9d/Backport.System.Threading.Lock/Lock.cs#L21

it's the same as the implementation for using `object`

lock-object

lock-Lock

and the `Lock` class would introduce more assembly metadata which is unnecessary and causes a deeper call stack

and here's the benchmark result from my device, it does not look better when handling concurrency lock operations

```

BenchmarkDotNet v0.14.0, Windows 11 (10.0.22631.3737/23H2/2023Update/SunValley3)
Intel Core Ultra 7 155H, 1 CPU, 22 logical and 16 physical cores
.NET SDK 9.0.100-preview.6.24328.19
  [Host]     : .NET 8.0.6 (8.0.624.26715), X64 RyuJIT AVX2
  DefaultJob : .NET 8.0.6 (8.0.624.26715), X64 RyuJIT AVX2


```
| Method                   | Mean          | Error         | StdDev        | Gen0       | Allocated     |
|------------------------- |--------------:|--------------:|--------------:|-----------:|--------------:|
| &#39;Using object&#39;           | 815,140.25 μs | 15,758.472 μs | 14,740.485 μs | 95000.0000 | 1171875.39 KB |
| System.Threading.Lock    | 761,921.09 μs | 15,147.605 μs | 14,169.079 μs | 95000.0000 | 1171875.39 KB |
| CountTo1000WithObject    |      96.91 μs |      0.989 μs |      0.925 μs |          - |       1.06 KB |
| CountTo1000WithLockClass |     100.86 μs |      2.010 μs |      3.921 μs |          - |       1.06 KB |

**Comment by MarkCiliaVincenti** [comment]
The problem there is the test (probably too little data) or the environment. In reality it should/must be doing the same thing, allocating the same memory (which is confirmed) and then using the exact same internal locking assembly code.

**Comment by MarkCiliaVincenti** [comment]
@WeihanLi a new version of Backport.System.Threading.Lock has come out that acts as a source generator and basically dropping the DLL as a dependency. If this new development makes you reconsider, I will amend this PR accordingly.

**Pull request closed without merging**
